### ISSUE TITLE
video instruction

### ISSUE THREAD

**Issue by chebyRUSHka** [jynnie/spectre-app#1]
Good day) I liked your idea and the program , I'm a little streamer on YouTube and would like to try your program , but I know little about programs , can you make a video review and insturktsiyu in more detail ? Sorry for my bad English and thanks in advance )

**Comment by chebyRUSHka** [comment]
I just do not understand this a little , I would like to try to play with subscribers in cs:go with your flashlight app )) I think subscribers will be interested . I watched the video on twitch , there opens the console and everything seems easy , but in fact something is unclear , and poorly versed in English

**Comment by jynnie** [comment]
Thanks for the interest! That's a great idea, I'll get to working on that.

**Comment by jynnie** [comment]
Do you need specific help with setup and/or usage?

**Comment by jynnie** [comment]
I've simplified installation now. You should be able to download a release for your OS from [releases](https://github.com/jynnie/spectre-app/releases). Then viewers can connect by going to [spectre.nextie.us](https://spectre.nextie.us/) and connecting to the room code that's in the top right corner of the Spectre App when you launch it. 

Let me know if this helps. I'll continue working on an instructional video though!

**Comment by jynnie** [comment]
Made an instructional video: https://youtu.be/4xnEr9n1jvk. Hope this helps!

**Comment by chebyRUSHka** [comment]
thanks a lot. )))
